ci:
  autofix_commit_msg: |
    :art: [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autoupdate_schedule: quarterly
  autoupdate_commit_msg: ":arrow_up: [pre-commit.ci] pre-commit autoupdate"

default_language_version:
  # Black recommends specifying the latest version of Python supported
  python: python3.12

exclude: "^{{ cookiecutter\\.project_name }}/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
