[tool.ruff]
select = ["ALL"]
ignore = [
    "E501",  # line too long, handled by black
    "COM",  # flake8-commas, handled by black
    "CPY",  # flake8-copyright
    "INP",  # flake8-no-pep420
]
src = ["src", "tests", "docs"]
target-version = "py38"  # the minimum Python version supported, used by pyupgrade

[tool.ruff.per-file-ignores]
"hooks/*.py" = [
    "D",  # pydocstyle
    "PLR0133",  # comparison-of-constant
    "S603",  # subprocess-without-shell-equals-true
    "S607",  # start-process-with-partial-path
]

[tool.ruff.isort]
known-first-party = [
  "{{ cookiecutter.project_name }}",
  "tests",
]
lines-between-types = 0
